config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/lists' => 'application#index'
  get '/lists/admin' => 'lists#admin'
  get '/goals' => 'application#index'
  get '/goals/all_goals' => 'goals#all_goals'
  get '/docs' => 'application#docs'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_effort' => 'goals#set_goal_effort'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'
  root 'application#index'
  resources :lists
  resources :goals
  resources :users, only: [:show, :edit, :update]

end

app/models/list.rb
class List < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :user
  has_many :goals
  markdownize! :description
  extend FriendlyId
  friendly_id :name, use: :slugged

  def to_param
    [id, name.parameterize].join("-")
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:admin, :edit]
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end


  def admin
    @lists = List.all
     render :template => 'lists/admin'
  end
  
  # GET /lists/1
  # GET /lists/1.json
  def show
    @title = @list.name
    @goals = @list.goals
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if current_user.try(:admin?)
        params_to_update = list_params_for_admins
      else
        params_to_update = list_params
      end
      if @list.update(params_to_update) 
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def require_admin
      unless can? :manage, @list
        flash[:error] = "You don't have sufficient privleges to access that page."
        redirect_to "/" 
      end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :user_id, :description, :rendered_description, :public, :user_ids => [])
    end

    def list_params_for_admins
      params.require(:list).permit(:name, :description, :rendered_description, :public, :user_ids => [])
    end

end

app/helpers/lists_helper.rb
module ListsHelper

  def status_board(list)

    good = Goal.health(1,list)
    medium = Goal.health(2,list)
    poor = Goal.health(3,list)
    unknown = Goal.health(0,list)
    
    capture_haml do
      if poor.count > 0
        haml_tag :span, class: "glyphicon glyphicon-fire text-danger" 
        haml_concat poor.count
        haml_tag :span, style: "padding-right:1.5em;"
      end

      if medium.count > 0
      haml_tag :span, class: "glyphicon glyphicon-warning-sign text-warning" 
      haml_concat medium.count
      haml_tag :span, style: "padding-right:1.5em;"
      end

      if good.count > 0
      haml_tag :span, class: "glyphicon glyphicon-ok text-success" 
      haml_concat good.count
      haml_tag :span, style: "padding-right:1.5em;"

      end

      if unknown.count > 0
      haml_tag :span, class: "glyphicon glyphicon-question-sign text-muted" 
      haml_concat unknown.count
      end

    end

  
      
  end

end

app/views/lists/_form.html.haml
= simple_form_for @list, :html => { :class => 'form-horizontal' } do |f|

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, autofocus: true, :class => 'form-control'
    = error_span(@list[:name])
  .form-group
    = f.label :description, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_area :description, :class => 'form-control', :style => "height:125px;"
      .help-block
        Markdown is okay here. 
    = error_span(@list[:description])
    = f.hidden_field :user_id, :value => current_user.id

  .form-group
    = f.label "Share with ...", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.collection_select :user_ids, User.all_except(current_user), :id, :full_name, {}, {:multiple => true, :class => 'form-control', 'style' => 'height:250px;'} 
      .help-block
        Select which registered users may view this list. 
      
  .form-group
    = f.label "Make this list public?", :class => 'col-sm-2 control-label'
    .col-sm-4.checkbox
      = f.check_box :public
      .help-block
        Selecting this will allow anyone to see this list if they have the URL,
        even if they're not a registered user. 
    
  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Save", :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), lists_path, :class => 'btn btn-default'

app/views/lists/_goals_button.html.haml
%a.btn.btn-success.btn-sm{:id => 'add_goals_toggle', 'data-backdrop' => 'false'}
  %span.glyphicon.glyphicon-plus-sign
    Add a Goal

app/views/lists/_goals_table.html.haml
%table.table.sortable
  %thead
    %tr
      - if params[:action] == "all_goals"
        %th List
      %th Health
      %th Goal
      %th Priority
      %th Support
      %th Effort
      %th Cost
      - if can? :manage, @list
        %th Manage
  %tbody{:id => "goals_table_body"}
    - goals.each do |goal|
      = render :partial => "goals/index_row", :locals => {:goal => goal} #, :context => context}

- if can? :manage, @list
  %a.btn.btn-success.btn-sm{:id => 'add_goals_toggle', 'data-toggle' => 'modal', 'data-target' => "#goalModal"}
    %span.glyphicon.glyphicon-plus-sign
    Add a Goal
  

app/views/lists/_goals_table_body.html.haml
- @goals.each do |goal|
  = render :partial => "goals/index_row", :locals => {:goal => goal}

app/views/lists/_list_list.html.haml
%h3
  Your Lists
%table.table
  %thead
    %tr
      %th
        List
      %th
        Description
      %th
        Goals Status
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @lists.each do |list|
      %tr
        %td= link_to list.name, list_path(list)
        %td
          != list.rendered_description
        %td
          = render :partial => "lists/status_board", :locals => {:list => list}

        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_list_path(list), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), list_path(list), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'


- if current_user.other_lists.count > 0
  %h3
    Lists Shared With You
  %table.table
    %thead
      %tr
        %th
          List
        %th
          Description
        %th
          Goals Status
        %th
    %tbody
      - @other_lists.each do |list|
        %tr
          %td= link_to list.name, list_path(list)
          %td
            != list.rendered_description
          %td
            = render :partial => "lists/status_board", :locals => {:list => list}



= link_to new_list_path, :class => 'btn btn-success btn-sm' do
  %span.glyphicon.glyphicon-plus-sign
  Make a List

app/views/lists/_no_authorization.html.haml
%div{:style => "margin-top:50px;"}
  .col-sm-6.col-sm-offset-3
    .panel.panel-danger
      .panel-heading.panel-danger
        %span.glyphicon.glyphicon-alert
        %strong
          You're not allowed to view this list. 
      .panel-body
        %p
          The owner of this list hasn't chosen to share it with you. Ask them to add you to the
          list by editing it and adding you to the user list.
          

app/views/lists/_no_lists.html.haml
%div{:style => "margin-top:50px;"}
  .col-sm-6.col-sm-offset-3
    .panel.panel-primary
      .panel-heading.panel-primary
        %strong
          You don't have any lists.
      .panel-body
        %p To use Priorities, you need to make a list. Lists can be named for:
        
        %ul.list-unstyled{:style => "margin-left:5em;margin-bottom:2em;"}
          %li{:style => "padding-top:1em;"}
            %span.glyphicon.glyphicon-user
            Teams you need to manage.
          %li{:style => "padding-top:1em;"}
            %span.glyphicon.glyphicon-list-alt
            A project you're working on. 
          %li{:style => "padding-top:1em;"}
            %span.glyphicon.glyphicon-check
            Groups of related work you need to prioritize. 

        = link_to new_list_path, :class => 'btn btn-success btn-sm', :style => "margin-left:6em;" do 
          %span.glyphicon.glyphicon-plus-sign
          Make A List

app/views/lists/_no_user.html.haml
%div{:style => "margin-top:50px;"}
  .col-sm-6.col-sm-offset-3
    .panel.panel-primary
      .panel-heading.panel-primary
        %strong
          You need to be logged in to use this page. 
      .panel-body
        %p This page is for the display of a user's goals. You must be logged in and 
           have a list set up with goals to view it. 
        

app/views/lists/_status_board.html.haml
= status_board(list)

app/views/lists/admin.html.haml
%h3
  All Lists
%table.table
  %thead
    %tr
      %th
        List
      %th
        Description
      %th
        Goals Status
      %th
        List Owner
        
      %th=t '.actions', :default => t("helpers.actions")
     
      %tbody
    - @lists.each do |list|
      %tr
        %td= link_to list.name, list_path(list)
        %td
          != list.rendered_description
        %td
          = render :partial => "lists/status_board", :locals => {:list => list}
        %td
          
          - if list.user
            = list.user.full_name
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_list_path(list), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), list_path(list), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/lists/edit.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/lists/index.html.haml
%h3
  Your Lists

%table.table
  %thead
    %tr
      %th
        List
      %th
        Description
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @lists.each do |list|
      %tr
        %td= link_to list.name, list_path(list)
        %td
          != list.rendered_description
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_list_path(list), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), list_path(list), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_list_path, :class => 'btn btn-primary'

app/views/lists/new.html.haml
- model_class = List
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/lists/show.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    = @list.name
  - if can? :manage, @list
    %li.inactive
      = link_to "Edit", edit_list_path
    
%div{:id => "goals_area"}
  - if cannot? :read, @list
    = render :partial => 'no_authorization.html.haml'
  - elsif @list.goals.count < 1 and can? :manage, @list
    = render :partial => 'no_goals.html.haml'
  - else
    = render :partial => 'goals_table.html.haml', :locals => {:goals => @list.goals, :context => "display_list"}
    
  
%div.modal.fade{:id => "goalModal", :role => "dialog", 'data-backdrop' => 'false'}
  %div.modal-dialog{:role => "document"}
    %div.modal-content
      %div.modal-header
        %button.close{"data-dismiss" => "modal", :id => "goals_toggle"}
          &times;
        %h4.modal-title
          %span.glyphicon.glyphicon-plus &nbsp;
          Create a Goal
      %div.modal-body
        = simple_form_for @list.goals.new, :remote => true, html: { id: "goalForm"} do  |f|
          = f.label :name
          = f.text_field :name, :autofocus => "autofocus", :id => "new_goal_name", :class => "form-control"
          = f.label :description
          %br
          = f.text_area :description, :rows => 10, :id => "new_goal_description", :class => "form-control"
          = f.hidden_field :list_id, :value => @list.id
          %br
          = f.button :submit, "Create Goal", :html => {"data-dismiss" => "modal", "data-backdrop" => "false", "id" => "goalSubmit"}, :class => "btn btn-primary"
      %div.modal-footer


%br
%br



:javascript

  $(document).on('hide.bs.modal', function (e) {
    $(e.target).removeData('bs.modal');
  });