config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/lists' => 'application#index'
  get '/lists/admin' => 'lists#admin'
  get '/goals' => 'application#index'
  get '/goals/all_goals' => 'goals#all_goals'
  get '/docs' => 'application#docs'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_effort' => 'goals#set_goal_effort'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'
  root 'application#index'
  resources :lists
  resources :goals
  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :goals, through: :lists

  def full_name
    if self.first_name && self.last_name
      return "#{self.first_name} #{self.last_name}"
    else
      return email
    end
  end

  scope :all_except, ->(user) { where.not(id: user) }

  
  def other_lists
    other_lists = List.includes(:users).where('users.id' => self.id).where.not('user_id' =>  self.id)
    return other_lists
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [:edit, :index]

  def show
    @user = User.find(params[:id])
    @title = "#{@user.email}"
  end

  def index
    @title = "Users"
    @users = User.all
  end


  def edit
    @user = User.find(params[:id])
    @title = @user.email
  end


  def update
    
    @user = User.find(params[:id])

    if params[:user][:password].blank?
        [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  
  private

  
  def require_admin
    unless current_user.try(:admin?)
      flash[:error] = "You must be an admin to access that page."
      redirect_to "/" 
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :id, :last_name, :email, :password, :password_confirmation)
  end
  
end

app/views/users/edit.html.haml
%h2
  Edit #{@user.email}
.bg-danger.text-danger

%br
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|

  .form-group
    = f.label "First Name", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :first_name, :class => 'form-control'

  .form-group
    = f.label "Last Name", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :last_name, :class => 'form-control'

  .form-group
    = f.label :email, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.email_field :email, autofocus: true , :class => 'form-control'

  .form-group
    = f.label 'New password', :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.password_field :password, autocomplete: "off" , :class => 'form-control'
      .help-block
        %i (leave blank if you don't want to change it)

  .form-group
    = f.label 'Confirm new password', :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control'

  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Update", :class => 'btn btn-primary'
-#      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default')

app/views/users/index.html.haml
%h1
  User List


%table.table
  %thead
    %tr
      %th
        User
      %th
        Email
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= user.full_name
        %td
          != user.email
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'