config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/lists' => 'application#index'
  get '/lists/admin' => 'lists#admin'
  get '/goals' => 'application#index'
  get '/goals/all_goals' => 'goals#all_goals'
  get '/docs' => 'application#docs'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_effort' => 'goals#set_goal_effort'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'
  root 'application#index'
  resources :lists
  resources :goals
  resources :users, only: [:show, :edit, :update]

end

app/models/goal.rb
class Goal < ActiveRecord::Base

  belongs_to :team
  belongs_to :list

  scope :priority, ->(priority,list) { where("priority = ? AND list_id = ?", priority, list.id) }
  scope :effort, ->(effort,list) { where("effort = ? AND list_id != ?", effort, list.id) }
  scope :low_risk, Proc.new { |area| area.support_status == 1 }
  scope :medium_risk, Proc.new { |area| area.support_status == 2 }
  scope :high_risk, Proc.new { |area| area.support_status == 3 }
  scope :unknown_risk, Proc.new { |area| area.support_status == 0 }
  scope :all_except, ->(goal) { where.not(id: goal) }

  markdownize! :description
  
  def self.health(health, list)
    goals = list.goals.select { |g| g.health == health}
    return goals
  end
    
  def self.cost(cost, list)
    goals = list.goals.select { |g| g.burden == cost}
    return goals
  end


  def burden
    if self.support == nil or self.effort == nil or  self.support == 0 or self.effort == 0 
      0
    else
      self.support + self.effort
    end
  end
  
  def health

    if self.priority == nil || self.support == nil || self.priority == 0 
      0
    elsif self.priority > self.support + 1
      3
    elsif self.priority > self.support
      2
    else
      1
    end
   
  end

  def priority_narrative
    case self.priority
    when 0
      "Undetermined"
    when 1
      "Low"
    when 2
      "Medium"
    when 3
      "High"
    end
  end

  def support_narrative
    case self.health
    when 0
      "at Unknown Risk"
    when 1
      "at Very Little Risk"
    when 2
      "at Some Risk"
    when 3
      "at High Risk"
    end
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]


  def all_goals
    @user = current_user ||= User.new
  end

  def set_goal_priority
    @priority = params[:priority]
    @goal = Goal.find(params[:goal])
    @goal.priority = @priority

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_priority_button.js.haml',
                           :locals => {:id => @goal.id,
                                       :priority => @goal.priority,
                                       :goal => @goal,
                                       :list => @goal.list}}
        format.html 
      end
    end
  end

 
  def set_goal_support
    @support = params[:support]
    @goal = Goal.find(params[:goal])
    @goal.support = @support

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_support_button.js.haml',
                           :locals => {:id => @goal.id,
                                       :support => @goal.support,
                                       :goal => @goal,
                                       :list => @goal.list}}
        format.html 
      end
    end
  end

 def set_goal_effort
    @effort = params[:effort]
    @goal = Goal.find(params[:goal])
    @goal.effort = @effort

    if @goal.save
      respond_to do |format|
        format.js { render :action => 'update_effort_button.js.haml',
                           :locals => {:id => @goal.id,
                                       :effort => @goal.effort,
                                       :goal => @goal,
                                       :list => @goal.list}}
        format.html 
      end
    end
 end


  
  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @list = @goal.list
    respond_to do |format|
      if @goal.save
        format.js {render :action => 'update_goals.js.haml', :locals => {:goals => @list.goals}}
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal.list, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @list = @goal.list
    @goal.destroy
    respond_to do |format|
      format.js {render :action => 'refresh_goals_list.js.haml', :object => @list, :locals => {:goals => @list.goals}}
#      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name,:list_id, :description, :team_id, :priority, :support, :effort)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
  
  def display_label(level, property)
    case level
    when 0
      label_class = "default"
      label = "No"
    when 1
      if property == "Health"
        label_class = "success"
        label = "Good"
      else
        label_class = "success"
        label = "Low"
      end
    when 2
      label_class = "warning"
      label = "Medium"
    when 3
      if property == "Effort" or property == "Priority"
        label_class = "danger"
        label = "High"
      elsif property == "Health"
        label_class = "danger"
        label = "Poor"
      end
    end

    capture_haml do
      haml_tag :span, class: "label-#{label_class} label" do
        haml_concat "#{label} #{property}"
      end
    end
  end

  def health_indicator(goal)
    case goal.health
    when 0
      glyph = "glyphicon-question-sign"
      indicator_class = "muted"
    when 1
      glyph = "glyphicon-ok"
      indicator_class = "success"
    when 2
      glyph = "glyphicon-warning-sign"
      indicator_class = "warning"
    when 3
      glyph = "glyphicon-fire"
      indicator_class = "danger"
    end
     capture_haml do
       haml_tag :span, class: "glyphicon #{glyph} text-#{indicator_class}"
     end    
  end


  def burden_label(goal)
    case goal.burden
    when 0
      label_class = "default"
      label = "No"
      glyph = "question-sign"
    when 1..2
      label_class = "success"
      label = "Low"
      glyph = "ok-sign"
    when 3..4
      label_class = "warning"
      label = "Medium"
      glyph = "warning-sign"
    when 5..6
      label_class = "danger"
      label = "High"
      glyph = "exclamation-sign"
    end
    capture_haml do
      haml_tag :span, class: "label-#{label_class} label" do
        haml_tag :span, class: "glyphicon glyphicon-#{glyph}"
        haml_concat "#{label} Cost"
      end
    end



  end

  def burden_indicator(goal)
    case goal.burden
    when 0
      indicator_class = "muted"
    when 1..2
      indicator_class = "success"
    when 3..4
      indicator_class = "warning"
    when 5..6
      indicator_class = "danger"
    end
    
    capture_haml do
      haml_tag :span, class: "label label-#{indicator_class}"
    end    
    
  end
  

  def goal_button_properties(goal,prop,list)
    case prop
    when "Support"
      goal_prop = goal.support
    when "Priority"
      goal_prop = goal.priority
    when "Effort"
      goal_prop = goal.effort
    end
    
    case goal_prop
    when 0
      if prop == "Effort"
        word = "No"
        btn_class = "default"
      else
        word = "No"
        btn_class = "danger"
      end
    when 1
      word = "Low"
      if prop == "Support"
        btn_class = "danger"
      else
        btn_class ="primary"
      end
    when 2
      word = "Medium"
      btn_class = "warning"
    when 3
      word = "High"
      if prop == "Support"
        btn_class = "success"
      else
        btn_class = "danger"
      end
    when nil
      btn_class = "default"
      if can? :manage, list
        word = "Set"
      else
        word = "Unset"
      end
    end
    return [btn_class, word]
  end




end

app/views/goals/_burden_field.html.haml
= burden_label(goal)

app/views/goals/_priority_button.html.haml
.btn-group.btn-group-xs

  - properties = goal_button_properties(goal, "Priority", list)

  %button{:type => "button", "data-toggle" => "dropdown", :class => "dropdown-toggle btn-xs btn btn-#{properties[0]}"}
    = properties[1]
    = "Priority"
    - if can? :manage, list
      %span.caret
  - if can? :manage, list
    %ul.dropdown-menu{:role => "menu"}
      - {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}.each do |l,n|
        %li
          =link_to goals_set_goal_priority_path(:goal => goal, :priority => n), :remote => true, :method => :post do
            = l

app/views/goals/_support_button.html.haml
.btn-group.btn-group-xs
  - properties = goal_button_properties(goal, "Support", list)

  %button{:type => "button", "data-toggle" => "dropdown", :class => "dropdown-toggle btn-xs btn btn-#{properties[0]}"}
    = properties[1]
    = "Support"
    - if can? :manage, list
      %span.caret
  - if can? :manage, list
    %ul.dropdown-menu{:role => "menu"}
      - {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}.each do |l,n|
        %li
          =link_to goals_set_goal_support_path(:goal => goal, :support => n), :remote => true, :method => :post do
            = l

app/views/goals/all_goals.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    All Goals
    
%div{:id => "goals_area"}
  - if user_signed_in? == false
    = render :partial => 'no_user.html.haml'
  - else
    = render :partial => 'lists/goals_table.html.haml', :locals => {:goals => current_user.goals}
    
  

%br
%br

app/views/goals/destroy_goal.js.haml
$("#goal_row_#{goal_id}").remove();

app/views/goals/edit.html.haml
%h1
  = "Editing #{@goal.name}"

= render 'form'

app/views/goals/index.html.haml
%h1 Listing goals

%table
  %thead
    %tr
      %th Name
      %th Kind
      %th
      %th
      %th

  %tbody
    - @goals.each do |goal|
      %tr
        %td= goal.name
        %td= goal.kind
        %td= link_to 'Show', goal
        %td= link_to 'Edit', edit_goal_path(goal)
        %td= link_to 'Destroy', goal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Goal', new_goal_path

app/views/goals/new.html.haml
%h1 New goal

= render 'form'

= link_to 'Back', goals_path

app/views/goals/refresh_goals_list.js.haml
$('#goals_table_body').html("#{j render(:partial => 'goals/goals_table_body', :locals => {:goals => @list.goals})}");

app/views/goals/show.html.haml
%p#notice= notice

%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to @goal.list.name, @goal.list
  %li.active
    = @goal.name
  - if can? :manage, @goal 
    %li
      = link_to edit_goal_path(@goal) do
        Edit
    
%h2
  = @goal.name

-# some day users may come back
-# - if @area.users.count > 0 
-#   %p.text-muted
-#     %span.glyphicon.glyphicon-user
-#     != @area.users.collect {|user| link_to user.handle, user}.to_sentence
  
!= @goal.rendered_description


%hr

%h3
  = "Goals Similar to #{@goal.name}"
.col-md-3
  %h4
    != "#{display_label(@goal.priority, 'Priority')}"
  %ul.list-unstyled
    - Goal.all_except(@goal).priority(@goal.priority, @goal.list).each do |a|
      %li
        = link_to a.name, a
    
.col-md-3
  %h4
    != "#{display_label(@goal.health, 'Health')}"
  %ul.list-unstyled
    - Goal.all_except(@goal).health(@goal.health, @goal.list).each do |a|
      %li
        = link_to a.name, a

.col-md-3
  %h4
    != "#{burden_label(@goal)}"
  %ul.list-unstyled
    - Goal.all_except(@goal).cost(@goal.burden, @goal.list).each do |g|
      %li
        = link_to g.name, g

.col-md-3
  %h4
    != "#{display_label(@goal.effort, 'Effort')}"
  %ul.list-unstyled
    - Goal.all_except(@goal).effort(@goal.effort, @goal.list).each do |a|
      %li
        = link_to a.name, a

app/views/goals/update_effort_button.js.haml
$("#effort_button-#{id}").html("#{j render(:partial => 'goals/effort_button', :locals => {:goal => goal, :list => list})}");
$("#td_effort_#{id}").attr("data-value", "#{effort}");
$("#td_effort_#{id}").parent('tr').attr("data-effort", "#{effort}");
$("#td_goal_burden_#{id}").html("#{j render(:partial => 'goals/burden_field', :locals => {:goal => goal, :list => list})}");
$("#td_goal_burden_#{id}").attr("data-value", "#{goal.burden}");

app/views/goals/update_goals.js.haml
$('#goalModal').modal('hide');
$("#goalForm")[0].reset();
$('#goals_area').html("#{j render(:partial => 'lists/goals_table', :locals => {:goals => goals})}");

app/views/goals/update_priority_button.js.haml
$("#priority-button-#{id}").html("#{j render(:partial => 'goals/priority_button', :locals => {:list => list, :goal => goal})}");
$("#td_priority_#{id}").attr("data-value", "#{priority}");
$("#td_priority_#{id}").parent('tr').attr("data-priority", "#{priority}");
$("#goal_health_#{id}").html("#{j render(:partial => 'goals/health_field', :locals => {:goal => goal})}");
$("#goal_health_#{id}").attr("data-value", "#{goal.health}");
$("#td_goal_burden_#{id}").html("#{j render(:partial => 'goals/burden_field', :locals => {:goal => goal, :list => list})}");
$("#td_goal_burden_#{id}").attr("data-value", "#{goal.burden}");

app/views/goals/update_support_button.js.haml
$("#support_button-#{id}").html("#{j render(:partial => 'goals/support_button', :locals => {:goal => goal, :list => list})}");
$("#td_support_#{id}").attr("data-value", "#{support}");
$("#td_support_#{id}").parent('tr').attr("data-support", "#{support}");
$("#goal_health_#{id}").html("#{j render(:partial => 'goals/health_field', :locals => {:goal => goal})}");
$("#goal_health_#{id}").attr("data-value", "#{goal.health}");
$("#td_goal_burden_#{id}").html("#{j render(:partial => 'goals/burden_field', :locals => {:goal => goal, :list => list})}");
$("#td_goal_burden_#{id}").attr("data-value", "#{goal.burden}");