config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/lists' => 'application#index'
  get '/lists/admin' => 'lists#admin'
  get '/goals' => 'application#index'
  get '/goals/all_goals' => 'goals#all_goals'
  get '/docs' => 'application#docs'
  get '/users/' => 'users#index'
  match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
  post 'goals/set_goal_priority' => 'goals#set_goal_priority'
  post 'goals/set_goal_effort' => 'goals#set_goal_effort'
  post 'goals/set_goal_support' => 'goals#set_goal_support'
  post 'goals/set_goal_work' => 'goals#set_goal_work'
  root 'application#index'
  resources :lists
  resources :goals
  resources :users, only: [:show, :edit, :update]

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title
      = "Priorities: #{@title}"
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag    'application', media: 'all', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    :css
      body {padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */}
      .panel-body blockquote {font-size: small;}
    %link{:href => "/css/bootstrap-responsive.css", :rel => "stylesheet"}/
  / Le fav and touch icons
  %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
  %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
  %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
  %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/

  %body
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{:type => "button", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Priorities
          %ul.nav.navbar-nav

            - if current_user
              %li.dropdown
                %a{:href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown", :role => "button"}
                  Your Lists
                  %span.caret
                  %ul.dropdown-menu{:role => "menu"}
                    - current_user.lists.each do |list|
                      %li
                        = link_to list.name, list
                    %li{:role => "presentation", :class => "divider"}
                    %li
                      = link_to "Create New List", new_list_path
                    - if current_user.try(:admin?)
                      %li
                        = link_to "List Admin", lists_admin_path


            %li.dropdown
              %a{:href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown", :role => "button"}
                About
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a{:href => "/docs"}
                    Documentation
                %li
                  %a{:href => "https://github.com/pdxmph/priorities"}
                    Source
                %li
                  %a{:href => "https://github.com/pdxmph/priorities/issues"}
                    Known Issues
                %li
                  %a{:href => "http://mph.puddingbowl.org/2016/02/thinking-about-priorities/"}
                    Thinking About Priorities
                    

                 
        .collapse.navbar-collapse

          %ul.nav.navbar-nav.navbar-right        
            - if user_signed_in? == false 
              %li
                %span
                  %a.btn.btn-primary.btn-xs.navbar-btn{:id => "signin_button", :href => new_user_session_path}
                    Sign In
            -else
              %li
                %p.navbar-text
                  %span.glyphicon.glyphicon-user 
                  = link_to current_user.full_name, edit_user_registration_path(current_user), :style => "color:white;"

              %li
                &nbsp;
              %li
                %div
                  = link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'navbar-btn btn  btn-danger btn-xs'


  .container
    = bootstrap_flash
    = yield
  
  :javascript
  
    $( document ).ready(function() {
    $.bootstrapSortable(true);
    });

    
    // Every time a modal is shown, if it has an autofocus element, focus on it.
    $( document ).on('shown.bs.modal', function() {
    $(this).find('[autofocus]').focus();
    });